// Renders docs/OSC.md from shared/osc-schema.ts. `npm run docs:osc`.
// The doc is generated so it cannot drift from what the server sends.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { CAM_FIELDS, CAM_MESSAGES, EVENT_MESSAGES, GLOBAL_FIELDS, MIX_FIELDS, MUTABLE, OSC_SCHEMA_VERSION, PER_FIELD_MESSAGES, SAMPLE_FIELDS, SWARM_FIELDS, typeTags } from '../shared/osc-schema';
import type { Field, MessageDoc } from '../shared/osc-schema';

const fieldTable = (fields: Field[]): string => [
  '| # | field | type | unit | meaning |',
  '|---|---|---|---|---|',
  ...fields.map((f, i) => `| ${i + 1} | \`${f.name}\` | ${f.type} | ${f.unit || '—'} | ${f.description} |`),
].join('\n');

const messageTable = (msgs: MessageDoc[]): string => [
  '| address | arguments | when | meaning |',
  '|---|---|---|---|',
  ...msgs.map((m) => `| \`${m.address}\` | ${m.args} | ${m.when} | ${m.description} |`),
].join('\n');

const md = `# HIVE OSC protocol — version ${OSC_SCHEMA_VERSION}

<!-- Generated by \`npm run docs:osc\` from shared/osc-schema.ts. Do not edit by hand. -->

Everything the HIVE backend sends over UDP, to every target enabled on the
dashboard (default \`127.0.0.1:9000\`; add your laptop's IP there). OSC 1.0,
one bundle per sample, big-endian, types \`i\` int32, \`f\` float32, \`s\` string.

Two shapes carry the same per-sample data. Use whichever suits your tool;
both are on by default and can be switched off on the dashboard.

## Identity

- **\`uid\`** — 8 characters, stable for a phone across reconnects and server
  restarts (derived from an id stored in the phone's browser). Use this when a
  *person* matters.
- **\`slot\`** — small integer 1..N, session-local, freed when a phone leaves
  and reused by the next joiner. Use this for \`route 1 2 3\`-style patching.

\`/hive/join\`, \`/hive/leave\` and the once-a-second \`/hive/roster\` map between them.

## \`/hive/sample\` — the wide message (${SAMPLE_FIELDS.length} arguments)

One per sensor sample per phone, ~60 Hz per phone. Type tags: \`${typeTags(SAMPLE_FIELDS)}\`.

${fieldTable(SAMPLE_FIELDS)}

**Compatibility rule:** fields are only ever appended. New server-side
features (there will be more — everything is computed here, phones send raw
sensors only) arrive as new columns at the end; \`/hive/schema\` carries the
version. A patch that unpacks the first ${SAMPLE_FIELDS.length} keeps working.

Axes: x = phone's right, y = phone's top, z = out of the screen. Raw
acceleration includes gravity and is sign-normalized so a flat, screen-up
phone reads \`acc_z ≈ +9.81\` on iOS and Android alike. People can flip
individual axes on their phone if the direction feels wrong to them.

### Processed signals

- **rel** — acceleration smoothed with a *One-Euro filter* and taken relative
  to an *adaptive zero*. The One-Euro filter (Casiez et al. 2012) is a low-pass
  whose cutoff rises with the speed of change: at rest it sits at
  \`filter: min cutoff\` (dashboard, default 1 Hz) and the jitter is gone; the
  faster the signal moves, the higher the cutoff (\`filter: beta\`, default
  0.3 per m/s² per s), so quick gestures arrive without lag. The zero: once a
  phone has been at rest for \`zero: rest before\` seconds (default 1.2 s) it
  slides toward the resting value with time constant \`zero: slide time\`
  (default 2.5 s). So \`rel\` is 0 whenever someone holds still — at any
  angle — and only *change* produces signal.
- **activity** — max of turning rate / 150 °/s and acceleration change / 6
  m/s², smoothed ~250 ms, clamped 0..1.
- **idle** — seconds since activity last dropped below 0.06.
- **turn** (v2) — the gyroscope projected onto the smoothed gravity direction:
  the rotation rate about the room's vertical, whether the phone lies flat
  (then it equals \`gyro_z\`), stands in a pocket, or is held at an angle.
  Turning on the spot is the same signal for everyone.

## \`/hive/swarm\` — the whole swarm (${SWARM_FIELDS.length} arguments)

At the swarm rate (dashboard, default 30 Hz). Type tags: \`${typeTags(SWARM_FIELDS)}\`.

${fieldTable(SWARM_FIELDS)}

## \`/hive/global\` — swarm meta-parameters (${GLOBAL_FIELDS.length} arguments, v3)

The whole hive as one signal, at the swarm rate. Where \`/hive/swarm\` says *how
much*, this says *how*: alike or not, in step or not, what rhythm, everyone or
a soloist. Type tags: \`${typeTags(GLOBAL_FIELDS)}\`. Each field also comes as
\`/hive/global/<name> f\`.

${fieldTable(GLOBAL_FIELDS)}

Windows: the correlation and phase features look at the last second per phone;
tempo, centroid and crest at ~4 s / ~2 s of the swarm's mean |rel| sampled at
the swarm rate. All zero with fewer than two phones (tempo/centroid need one).

## \`/hive/cam\` — the room as the camera sees it (${CAM_FIELDS.length} arguments, v3)

From \`backend/vision/hive_vision.py\` (YOLO pose on a webcam, see the backend
README) at the camera's frame rate, only while it is attached. Type tags:
\`${typeTags(CAM_FIELDS)}\`. People here are anonymous tracker ids — they are
never matched to phones; someone can be in the picture without a phone or in
the hive without being in the picture. Coordinates are 0..1 of the frame,
mirrored when the dashboard says so.

${fieldTable(CAM_FIELDS)}

${messageTable(CAM_MESSAGES)}

The last eight fields are the crowd's *motion*, computed on the server from
frame to frame: where it drifts (flow), how disordered (turbulence), whether
people move alike (moveSync), whether they come together (converge < 0), how
close they stand (nearest), how many stand still, how much of the room is used.

## \`/hive/mix\` — bees ⇄ camera (${MIX_FIELDS.length} arguments, v3)

Where the swarm on the wall and the crowd in the picture meet. Both are 0..1
across their picture, so the server can relate them even though nobody is
matched to a phone. At the swarm rate; each field also as \`/hive/mix/<name>\`.

${fieldTable(MIX_FIELDS)}

## Switching things off

Every family has a switch on the dashboard (settings: *osc …*), and every
small message has its own chip under *osc parameters* — off means not sent,
which saves Wi-Fi traffic for whatever nobody patches. Mutable keys:
${MUTABLE.map((m) => `\`${m.key}\``).join(', ')}.

**REAPER** as a target: add this laptop's IP + port on the dashboard; in REAPER
*Options → Preferences → Control/OSC/Web → Add → OSC*, mode *Receive only*, that
port. On a plugin parameter *Param → Learn*, move in front of the camera, and it
binds to e.g. \`/hive/cam/energy\` — smooth it in REAPER's parameter modulation.

## Events and housekeeping

${messageTable(EVENT_MESSAGES)}

## Per-field messages

Same data as \`/hive/sample\`, one small message per quantity, addressed by slot.

${messageTable(PER_FIELD_MESSAGES)}

## Receiving

**Pure Data** (vanilla ≥ 0.46) — \`examples/hive-receive.pd\`:

\`\`\`
[netreceive -u -b 9000] → [oscparse] → [list trim] → [route hive] → [route sample swarm join leave roster]
  sample → [unpack f s f f f f f f f f f f f f f f f]   (${SAMPLE_FIELDS.map((f) => f.name).join(' ')})
\`\`\`
oscparse turns \`s\` into symbols and \`i\`/\`f\` into floats.

**Max/MSP:** \`[udpreceive 9000]\` → \`[route /hive/sample]\` → \`[unpack i s f f f …]\`.

**SuperCollider:** \`thisProcess.openUDPPort(9000); OSCdef(\\\\hive, { |msg| msg.postln }, '/hive/sample');\`

**Python:** \`python3 examples/osc_listen.py 9000\` prints everything (no dependencies), or
skip OSC and read JSON from \`ws://<mac>:8080/feed\` with \`examples/feed_client.py\`.

Press **Ping** next to your target on the dashboard: \`/hive/ping\` arrives if the route works.
`;

const out = resolve(import.meta.dirname, '..', 'docs', 'OSC.md');
writeFileSync(out, md);
console.log(`wrote ${out}`);
